-- SELECT * FROM customer
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue 
FROM customer GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount 
FROM customer WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, 
	ROUND(AVG(review_rating::numeric), 2) AS avg_review_rating 
FROM customer 
GROUP BY item_purchased 
ORDER BY avg_review_rating DESC 
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount::numeric), 2) AS avg_purchase_amount 
FROM customer WHERE shipping_type IN('Express', 'Standard')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? 
--Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
	CASE 
		WHEN subscription_status='Yes' THEN 'Subscriber' 
		ELSE 'Non-subscriber' 
	END subscription_status, 
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount::numeric), 2) AS avg_spend, 
	ROUND(SUM(purchase_amount::numeric), 2) AS total_revenue 
FROM customer 
GROUP BY subscription_status
ORDER BY avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
	ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(customer_id), 2) AS percentage_of_purchases
FROM customer 
GROUP BY item_purchased
ORDER BY percentage_of_purchases DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
;WITH cust_type AS
(SELECT 
	CASE 
		WHEN previous_purchases=1 THEN 'New' 
		WHEN previous_purchases > 1 AND previous_purchases <= 10 THEN 'Returning'
		ELSE 'Loyal' 
	END AS customer_type
FROM customer)

SELECT *, COUNT(*) AS total_customer FROM cust_type
GROUP BY customer_type;

--Q8. What are the top 3 most purchased products within each category? 
;WITH item_category AS
(SELECT category, item_purchased,
COUNT(customer_id) AS total_purchase,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer 
GROUP BY category, item_purchased)

SELECT * FROM item_category
WHERE item_rank <= 3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
	COUNT(customer_id) AS repeat_buyers 
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

--Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;
